// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1SqrXbfn8HPC3BB5c7XSIF4xSb5G9zA',
    appId: '1:656416273390:web:104b1ccdb236e9002ed4ff',
    messagingSenderId: '656416273390',
    projectId: 'mobile-app-d246c',
    authDomain: 'mobile-app-d246c.firebaseapp.com',
    storageBucket: 'mobile-app-d246c.firebasestorage.app',
    measurementId: 'G-NFHJZPZFE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hUE5TTqsT0m2bVakOtJ-X1-HJD7gKhw',
    appId: '1:656416273390:android:65accf53ff893e0b2ed4ff',
    messagingSenderId: '656416273390',
    projectId: 'mobile-app-d246c',
    storageBucket: 'mobile-app-d246c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvyHUVKkoyp3iFNERGlfhqIewf-A-OW9M',
    appId: '1:656416273390:ios:aba998a8a95d8f542ed4ff',
    messagingSenderId: '656416273390',
    projectId: 'mobile-app-d246c',
    storageBucket: 'mobile-app-d246c.firebasestorage.app',
    iosBundleId: 'com.example.gbpnDealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvyHUVKkoyp3iFNERGlfhqIewf-A-OW9M',
    appId: '1:656416273390:ios:aba998a8a95d8f542ed4ff',
    messagingSenderId: '656416273390',
    projectId: 'mobile-app-d246c',
    storageBucket: 'mobile-app-d246c.firebasestorage.app',
    iosBundleId: 'com.example.gbpnDealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK1SqrXbfn8HPC3BB5c7XSIF4xSb5G9zA',
    appId: '1:656416273390:web:ffbe6d358ad730ba2ed4ff',
    messagingSenderId: '656416273390',
    projectId: 'mobile-app-d246c',
    authDomain: 'mobile-app-d246c.firebaseapp.com',
    storageBucket: 'mobile-app-d246c.firebasestorage.app',
    measurementId: 'G-HJ3P47NP8L',
  );
}
