// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqELsC-ms-8tbMQTtQGEJCIXY22qP1L-s',
    appId: '1:230438338034:web:5c4fbf8a6ff7005389ff6b',
    messagingSenderId: '230438338034',
    projectId: 'gbpd-8468e',
    authDomain: 'gbpd-8468e.firebaseapp.com',
    storageBucket: 'gbpd-8468e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuy7oaIv7z6M02fThizpCygu95XJckbMY',
    appId: '1:230438338034:android:5a253950cda4aba589ff6b',
    messagingSenderId: '230438338034',
    projectId: 'gbpd-8468e',
    storageBucket: 'gbpd-8468e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPp8Xx8o4O4v4OghMpC_R5a45DaZnSVC4',
    appId: '1:230438338034:ios:5741f00926e8659e89ff6b',
    messagingSenderId: '230438338034',
    projectId: 'gbpd-8468e',
    storageBucket: 'gbpd-8468e.firebasestorage.app',
    iosBundleId: 'com.example.gbpnDealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPp8Xx8o4O4v4OghMpC_R5a45DaZnSVC4',
    appId: '1:230438338034:ios:5741f00926e8659e89ff6b',
    messagingSenderId: '230438338034',
    projectId: 'gbpd-8468e',
    storageBucket: 'gbpd-8468e.firebasestorage.app',
    iosBundleId: 'com.example.gbpnDealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqELsC-ms-8tbMQTtQGEJCIXY22qP1L-s',
    appId: '1:230438338034:web:188e5336cdf81f9689ff6b',
    messagingSenderId: '230438338034',
    projectId: 'gbpd-8468e',
    authDomain: 'gbpd-8468e.firebaseapp.com',
    storageBucket: 'gbpd-8468e.firebasestorage.app',
  );
}
